### ISSUE TITLE
Why package.json and app.json?

### ISSUE THREAD

**Issue by rblakeley** [heroku/node-js-sample#72]
These two files have significant content overlap. What is the reason or purpose for having both?

**Comment by markpundsack** [comment]
App.json is used by the Heroku Button for deployment on Heroku, although in this case, there's little useful content in it and yes, it's mostly redundant with package.json. I think the only content that's used is the icon.

**Comment by zeke** [comment]
:see_no_evil:

**Comment by rblakeley** [comment]
`"icon"` is a valid package.json property ([reference](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json#icon)).  
This may not be the right place to address the issue, but couldn't Heroku just get the content it wants from package.json?

**Comment by markpundsack** [comment]
I guess it's possible, but the Heroku Button needs to work for Rails, Java, and other apps, which don't generally have a package.json file. We did debate internally whether we should just use package.json instead of a separate file, but the separate app.json won.

**Comment by zeke** [comment]
Not that it matters much, but the above-mentioned package.json reference is not about the package.json used by node and npm. That one is here: https://docs.npmjs.com/files/package.json

We have a related discussion going on the npm website repo about logos/icons: https://github.com/npm/newww/issues/291

**Comment by rblakeley** [comment]
Thanks @zeke for correcting the reference and thanks @markpundsack for the background.

Just my two cents but seems like those other apps (Rails, Java, etc.) are still going to be adding a new file to their project, so why not call it package.json? I think the conceptual burden is understanding that there is now a JSON file in the root that profiles the application. Calling it app.json instead of package.json doesn't make it any more obvious than just looking at the contents.

It's a minor issue, but I'm just averse to having to update information in two places and having an extra file in the project root. Seeing a dozen process/environment/task files in the root triggers an intense jaw clench.

**Comment by zeke** [comment]
I know how you feel. I campaigned for `package.json` but was quickly labeled a node sympathizer. :)

Hopefully you don't have a `bower.json` in your project too, but if you do, see https://www.npmjs.com/package/sellout
