### ISSUE TITLE
Button does not work

### ISSUE THREAD

**Issue by FZambia** [heroku/node-js-sample#78]
Hello!

When I click button in this repo I get:

```
No app-5c96aa6a5be707f4ff05e1d8c66f0570.json located in the repo URL provided.
Make sure that an app-5c96aa6a5be707f4ff05e1d8c66f0570.json file exists in the project root directory.
```

centrifugal/centrifugo#14

**Comment by FZambia** [comment]
Works again:)

**Comment by olgapereda125** [comment]
??

**Comment by FZambia** [comment]
@olgapereda125 durung that day Heroku button click resulted in error message above on Heroku side. Then the problem went away.

**Comment by olgapereda125** [comment]
Ok i get that but... i dont understand why i recibe this mail ...
