### ISSUE TITLE
npm-shrink wrap confusing

### ISSUE THREAD

**Issue by mlynch** [heroku/node-js-sample#79]
Is the shrinkwrap file necessary? Imagine my frustration when heroku failed to find a new module I installed and added to `package.json`, because the shrinkwrap file had already fixed the plugins in time. Took quite a while to realize what was going on.

**Comment by markpundsack** [comment]
Removed the shrinkwrap for now. I'm always shocked this isn't standard on all projects, but I'll save that for another day.
