### ISSUE TITLE
node-js-sample fails git push due to shrinkwrap hard coded ip address host down

### ISSUE THREAD

**Issue by ai7** [heroku/node-js-sample#83]
The hard coded ip address in npm-shrinkwrap.json is not responding. This results in git push to fail with a timeout error message after a long delay.

remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json + shrinkwrap)
remote:        npm ERR! fetch failed http://174.129.255.150:4873/mime-types/-/mime-types-2.0.10.tgz
remote:        npm ERR! fetch failed http://174.129.255.150:4873/mime-types/-/mime-types-2.0.10.tgz
remote:        npm ERR! fetch failed http://174.129.255.150:4873/mime-types/-/mime-types-2.0.10.tgz
remote:        npm ERR! Linux 3.13.0-61-generic
remote:        npm ERR! argv "/tmp/build_255e09f531e5b58d25519c3549f33d3e/.heroku/node/bin/node" "/tmp/build_255e09f531e5b58d25519c3549f33d3e/.h
eroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_255e09f531e5b58d25519c3549f33d3e/.npmrc"
remote:        npm ERR! node v0.12.2
remote:        npm ERR! npm  v2.7.4
remote:        npm ERR! code ETIMEDOUT

I tried to ping the host and it appears down:

[0 ubuntu@somehost ~/proj/bitstarter]$ nmap -p 4873 174.129.255.150
Starting Nmap 6.40 ( http://nmap.org ) at 2015-08-28 12:42 PDT
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.03 seconds

The host appears to be an aws ip:
150.255.129.174.in-addr.arpa domain name pointer ec2-174-129-255-150.compute-1.amazonaws.com

Can we please have this fixed so we can get on with our heroku learning? ;) This was working like 1-2 weeks ago.

**Comment by yoshiokatsuneo** [comment]
I got the same error, and could workaround by removing the file("npm-shrinkwrap.json"):

% cd node-js-sample
% git rm npm-shrinkwrap.json
% git commit -m "Removed npm-shrinkwrap.json"

**Comment by markpundsack** [comment]
Removed the shrinkwrap for now. I'm always shocked this isn't standard on all projects, but I'll save that for another day.

**Comment by olgapereda125** [comment]
Can you tell me why i'm recibing these messages? I don't understand a thing!

**Comment by markpundsack** [comment]
@olgapereda125 You likely starred or watched this repo or subscribed to this issue.
